apiVersion: apps/v1
kind: Deployment
metadata:
  name: catalog
spec:
  template:
    spec:
      containers:
        - name: catalog
          env:
            - name: RETAIL_CATALOG_PERSISTENCE_PROVIDER
              value: mysql
            - name: RETAIL_CATALOG_PERSISTENCE_ENDPOINT
              valueFrom:
                secretKeyRef:
                  name: catalog-db-secret
                  key: endpoint
            - name: RETAIL_CATALOG_PERSISTENCE_USER
              valueFrom:
                secretKeyRef:
                  name: catalog-db-secret
                  key: username
            - name: RETAIL_CATALOG_PERSISTENCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: catalog-db-secret
                  key: password
